### PR TITLE
Support yarn git dependencies

### PR DESCRIPTION
**Pull request by rvem**
Problem: Currently dependencies from github or git directly cannot be fetched.

Solution:
1) Rework fetcher to fetch git repository when dependency should be
   taken directly from git repository
2) Update yarn cache builder to create tarballs with the names expected
   by yarn for github and direct git dependencies.

### CODE REVIEW

**Review by PhilTaken — APPROVED** [review]
The nix part looks really good to me.

Not too sure about the javascript parts but the logic is sound.

**Comment by cab404** [comment]
pushed a small failing test. you can reproduce it's env by adding a git dep with 
```
yarn add git+ssh://git@github.com:left-pad/left-pad.git
```

**Comment by rvem** [comment]
CI can't ssh :(
Can you try with https instead?

**Comment by cab404** [comment]
wow that's dumb. it won't fail on https :D

**Comment by cab404** [comment]
@rvem error is not related to CI not being able to ssh
```
ssh: Could not resolve hostname github.com:left-pad: Name or service not known
```

**Comment by rvem** [comment]
Ugh, okay, will take a look then 😄

**Comment by rvem** [comment]
Pofixeel, but only for `yarn`. Now `npm` tests are failing :disappointed:

**Comment by rvem** [comment]
Though, CI still can't ssh :joy:

**Pull request merged**
