### PR TITLE
Add cache argument to `npm prune`

### PR DESCRIPTION
**Pull request by zhenyavinogradov**

### CODE REVIEW

**Comment by mkaito** [comment]
Could you please explain why?

**Comment by zhenyavinogradov** [comment]
Without the argument `npm prune` tries to create the cache in the home directory. I don't know what the cache is used for. I've removed the argument in another PR and didn't notice it breaking things because on my system it somehow succeded to create the `/homeless-shelter` directory

**Comment by yorickvP** [comment]
You should enable the nix sandbox.

**Comment by zhenyavinogradov** [comment]
It is enabled, but for some reason I have write access to / inside the sandbox

**Pull request merged**
